<a href="https://colab.research.google.com/github/yuktagupta/Anudip_foundation_python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr =np.array([1,2,3],dtype =np.int32)
print(arr)

[1 2 3]


In [ ]:
import numpy as np
arr =np.array([100,200,300],dtype =np.int64)
print(arr)

[100 200 300]


In [ ]:
import numpy as np
arr = np.array([1.0,2.5,3.7],dtype=np.float64)
print(arr)

[1.  2.5 3.7]


In [ ]:
import numpy as np
arr = np.array([1+ 2j,3 + 2j],dtype=np.complex128)
print(arr)

[1.+2.j 3.+2.j]


In [ ]:
import numpy as np
arr =np.array([True,False],dtype=np.bool)
print (arr)

[ True False]


In [ ]:
import numpy as np
arr = np.array(['apple',2,3.5] ,dtype=np.object_)
print(arr)

['apple' 2 3.5]


In [ ]:
import numpy as np
arr = np.array(['hello','world'] ,dtype=np.bytes_)
print(arr)

[b'hello' b'world']


In [ ]:
import numpy as np
date_arr=np.array(['2023-10-03', '2023-10-04'],dtype=np.datetime64)
print(date_arr)

['2023-10-03' '2023-10-04']


In [ ]:
import numpy as np
#Examplewithtimedelta64
time_diff=np.array(['1days', '3hours'],dtype=np.timedelta64)
print(time_diff)

ValueError: Could not convert object to NumPy timedelta

In [ ]:
import numpy as np
#Examplewithtimedelta64
# Changed the format of the strings to be compatible with timedelta64
time_diff = np.array(['1D', '3h'], dtype=np.timedelta64)
print(time_diff)

ValueError: Could not convert object to NumPy timedelta

In [ ]:
#CreatinganArrayfromaListorTuple
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array((4,5,6))
print("ArrayfromList:",arr1)
print("ArrayfromTuple:",arr2)

ArrayfromList: [1 2 3]
ArrayfromTuple: [4 5 6]


In [ ]:
#CreatinganArraywithaSpecifiedDataType
import numpy as np
arr=np.array([1,2,3],dtype=float)
print("ArraywithDataType:",arr)

ArraywithDataType: [1. 2. 3.]


In [ ]:
#CreatinganArraywithaRangeofValues
import numpy as np
#arr.np.array(10)
arr=np.arange(10)
print("ArraywithRangeofValues:",arr)

ArraywithRangeofValues: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
#CreatinganArrayofZerosorOnes
import numpy as np
zeros_arr=np.zeros((2,3))
ones_arr=np.ones((3,2))
print("ArrayofZeros:")
print(zeros_arr)
print("ArrayofOnes:")
print(ones_arr)

ArrayofZeros:
[[0. 0. 0.]
 [0. 0. 0.]]
ArrayofOnes:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#CreatinganArrayofZerosorOnes
import numpy as np
arr1=np.zeros(5)
arr2=np.ones(5)
print("ArrayofZeros:",arr1)
print("ArrayofOnes:",arr2)

ArrayofZeros: [0. 0. 0. 0. 0.]
ArrayofOnes: [1. 1. 1. 1. 1.]


In [ ]:
#CreatinganIdentityMatrix
import numpy as np
identity_matrix=np.eye(3)
print("IdentityMatrix:")
print(identity_matrix)

IdentityMatrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#.NumPyArrayIndexing
import numpy as np
arr = np.array ([1,2,4,5,6])
print("Element at index 0:", arr[0])
print("Element at index 0:", arr[2])

print("Last element:", arr[-1])
print("second-to-Last element:", arr[-2])
#slicing array
print("Elements from index 1 to 3:", arr[1:4])
#using slicing
print("Every second element:", arr[::2])

Element at index 0: 1
Element at index 0: 4
Last element: 6
second-to-Last element: 5
Elements from index 1 to 3: [2 4 5]
Every second element: [1 4 6]


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#np.rand(np.random.rand(3,3))
# Use np.random.rand() to generate random numbers
np.random.rand(3,3)*6

array([[4.11708455, 1.74549008, 5.8498449 ],
       [5.29776257, 2.93198142, 0.63964832],
       [2.72659688, 3.84826418, 3.18248148]])

In [ ]:
#array name[row_index,column_index]
# Create and assign an array to a variable
some_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Now you can index 'some_array'
print(some_array[1,1])

50


In [ ]:
##Hi! I am new to Python numpy. Can you generate some real world situations where I can use a numpyarray with some source code.
import numpy as np

# Daily temperatures (°C) for one week
temps = np.array([22.4, 24.1, 23.0, 25.6, 24.8, 26.1, 23.9])

# Find average, min, max
avg_temp = np.mean(temps)
min_temp = np.min(temps)
max_temp = np.max(temps)

print(f"Average Temperature: {avg_temp:.1f}°C")
print(f"Minimum Temperature: {min_temp}°C")
print(f"Maximum Temperature: {max_temp}°C")


Average Temperature: 24.3°C
Minimum Temperature: 22.4°C
Maximum Temperature: 26.1°C


# Numpy Slicing

In [ ]:
#Basic Slicing
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
#Extract elements from index 1 to 4 (exclusive)
sliced_array = arr[1:4]
print(sliced_array)

[1 2 3]


In [ ]:
#Step Slicing
sliced_array = arr[-3:]
print(sliced_array)

[3 4 5]


In [ ]:
#Multidimensional Array Slicing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row = arr[1, :]
print(row)
col = arr[:, 1]
print(col)

[4 5 6]
[2 5 8]


In [ ]:
#Boolean Indexing
condition = arr > 2
filtered_array = arr[condition]
print(filtered_array)

[3 4 5 6 7 8 9]


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr[1:4] = 10
print(arr)

[ 0 10 10 10  4  5]


In [ ]:
# NumPy Array Copy v/s View
original_array = np.array([1,2,3,4,5])
copied_array = original_array.copy()
copied_array[0] = 100
print("original_array:",original_array)
print("copied_array:",copied_array)

original_array: [1 2 3 4 5]
copied_array: [100   2   3   4   5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape =arr.shape
print("shape into the array :",shape)

shape into the array : (2, 3)


In [ ]:
#Reshaping with -1
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = arr.reshape(3, -1)
print("Reshaped array:")
print(reshaped_array)

Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#1. Hi! Let's create a real-life example involving weather data. Use NumPy to analyze temperature data for a week, perform slicing, indexing, shaping, and reshaping operations, and calculate various statistics.
import numpy as np
temperatures = np.array([
    [30.5, 32.0, 31.8, 33.2, 34.0, 32.5, 31.0],  # City A
    [25.0, 26.5, 27.2, 28.0, 27.8, 26.9, 25.5]   # City B
    ])

print("Original Temperature Data:\n", temperatures)


Original Temperature Data:
 [[30.5 32.  31.8 33.2 34.  32.5 31. ]
 [25.  26.5 27.2 28.  27.8 26.9 25.5]]


In [ ]:
#1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.
import numpy as np

zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.full(10 , 5)

print("Array of 10 Zeros:", zeros_array)
print("Array of 10 Ones:", ones_array)
print("Array of 10 Fives:", fives_array)


Array of 10 Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 Fives: [5 5 5 5 5 5 5 5 5 5]


In [ ]:
##Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix with Values from 2 to 10:")
print(matrix)

3x3 Matrix with Values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.
import numpy as np
zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.full(10, 5)
combined_array = np.concatenate([zeros_array, ones_array, fives_array])

In [ ]:
print("Combined Array:")
print(combined_array)

Combined Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]
